#!/usr/bin/env bash
#
# usage: replace-tag-and-doi [FILE]... 
# Replaces tags and DOIs used in the files [FILE]... with corresponding identifiers listed in the "release.sed" script.
set -e

if [ $# -lt 1 ]; then
    echo "usage: $0 [FILE]..."
    exit 1
fi

bindir="$(dirname "${0}")"

for filename in "${@}"; do
    sed -f ${bindir}/release.sed -i .backup ${filename}
done
